#!/bin/sh

DISPLAY=:0.0
export DISPLAY

if [ `/sbin/ifconfig eth0 | grep inet | grep -v inet6 | wc -l` -lt 1 ]; then
	echo "Your eth0 interface is not up, so let's not overcrowd the wifi..." >>  /home/gsacre/var/log/backup.log
	exit 1
fi

if [ `grep -i softkinetic /etc/resolv.conf | wc -l` -lt 1 ]; then
	echo "You are not on the Softkinetic network... I go back to sleep..." >> /home/gsacre/var/log/backup.log
        exit 2
fi

if [ ! -d /mnt/u/backup_home ]; then
	echo "Your personal folder is not mounted. Mounting..." >> /home/gsacre/var/log/backup.log
	mount /mnt/u
fi

if [ ! -d /mnt/u/backup_home ]; then
	echo "Ok, it seems we have a serious problem... Exiting..." >> /home/gsacre/var/log/backup.log
	exit 1
fi

notify-send -u low "BACKUP" "Starting cleanup PROJECTS backups"
echo "Cleanup of /home/gsacre/projects backup starting at `date`" >> /home/gsacre/var/log/backup.log
cat /home/gsacre/projects/list_of_projects_to_backup | while read project; do
        duplicity remove-older-than 12W file:///mnt/u/backup_projects/${project} >> /home/gsacre/var/log/backup.log
done
echo "Cleanup of /home/gsacre/projects backup finished at `date`" >> /home/gsacre/var/log/backup.log
notify-send -u low "BACKUP" "Ended cleanup PROJECTS backups"
