#!/bin/sh

DISPLAY=:0.0
export DISPLAY

if [ `/sbin/ifconfig eth0 | grep inet | grep -v inet6 | wc -l` -lt 1 ]; then
	echo "Your eth0 interface is not up, so let's not overcrowd the wifi..." >>  /home/gsacre/var/log/backup.log
	exit 1
fi

if [ `grep -i softkinetic /etc/resolv.conf | wc -l` -lt 1 ]; then
	echo "You are not on the Softkinetic network... I go back to sleep..." >> /home/gsacre/var/log/backup.log
        exit 2
fi

if [ ! -d /mnt/u/backup_mail ]; then
	echo "Your personal folder is not mounted. Mounting..." >> /home/gsacre/var/log/backup.log
	mount /mnt/u
fi

if [ ! -d /mnt/u/backup_mail ]; then
	echo "Ok, it seems we have a serious problem... Exiting..." >> /home/gsacre/var/log/backup.log
	exit 1
fi

notify-send -u low "BACKUP" "Starting cleanup of MAIL backups"
echo "Cleanup of /home/gsacre/Maildir backup starting at `date`" >> /home/gsacre/var/log/backup.log
duplicity remove-older-than 12W file:///mnt/u/backup_mail >> /home/gsacre/var/log/backup.log
echo "Cleanup of /home/gsacre/Maildir backup finished at `date`" >> /home/gsacre/var/log/backup.log
notify-send -u low "BACKUP" "Finished cleanup of MAIL backups"
