#!/bin/sh
xrandr --output VGA1 --auto
xrandr --output LVDS1 --off
xrandr --output HDMI1 --auto
xrandr --output VGA1 --right-of HDMI1
xset -b

#xrandr --output HDMI1 --auto --output VGA1 --auto --right-of HDMI1 --output LVDS1 --off
